- name: install zip
  apt:
    name: zip
    state: latest
    force: yes

- name: download wordpress
  get_url:
    url: "http://ja.wordpress.org/wordpress-{{ wp_version }}-ja.zip"
    dest: "/usr/local/src/wordpress-{{ wp_version }}-ja.zip"

- name: unzip wordpress
  unarchive:
    src: "/usr/local/src/wordpress-{{ wp_version }}-ja.zip"
    dest: "{{ wp_nginx_root }}"
    creates: "{{ wp_nginx_root }}/wordpress"
    owner: nginx
    group: nginx
    copy: no

- name: modify wp-config.php
  template:
    src: wp-config.php
    dest: "{{ wp_nginx_root }}/wordpress/wp-config.php"
    owner: nginx
    group: nginx
    mode: 0644

- include: nginx.yml
- include: mysql.yml
