- name: install python-mysqldb
  apt:
    name: python-mysqldb
    state: latest
    force: yes

- name: modify ~/.my.cnf
  template:
    src: mysql/my.cnf
    dest: ~/.my.cnf
    mode: 0600
  when: "wp_mysql_host != 'localhost'"

- name: modify mysql database
  mysql_db:
    login_host: "{{ wp_mysql_host }}"
    name: "{{ wp_mysql_database }}"
    state: present

- name: modify mysql user
  mysql_user:
    host: "{{ wp_mysql_host }}"
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: "{{ wp_mysql_database }}.*:ALL"
    state: present
