- name: modify ssl crt
  copy:
    src: ssl
    dest: /etc/nginx
    owner: root
    group: root
    mode: 0755

- name: modify nginx config
  template:
    src: nginx/wordpress.conf
    dest: /etc/nginx/conf.d/wordpress.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
